"""Role-permission - relation update

Revision ID: c5d1f51c2a5d
Revises: b9395f79ae6f
Create Date: 2024-07-06 12:42:30.220318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d1f51c2a5d'
down_revision: Union[str, None] = 'b9395f79ae6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
